#!/usr/bin/env bash
#Secure transfer of a file from source to destination
# Check if all required parameters are provided
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Retrieve parameters
file_path=$1
server_ip=$2
username=$3
ssh_key_path=$4

# Disable strict host key checking
SCP_OPTIONS="-o StrictHostKeyChecking=no"

# Transfer the file using scp
scp -i "$ssh_key_path" "$SCP_OPTIONS" "$file_path" "$username@$server_ip:~/"
