#!/usr/bin/env bash

# Update the package lists
sudo apt-get update -y

# Install Nginx
sudo apt-get install nginx -y

# Configure Nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart Nginx
sudo /etc/init.d/nginx restart

# Create an index.html file with "Hello World!" message
echo "Hello World!" | sudo tee /var/www/html/index.html
